spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: dnjswkd0731
    url: jdbc:mariadb://wonjang_db/wonjang_schema?serverTimezone=Asia/Seoul&useSSL=false&characterEncoding=utf8
    username: fada2020

  jpa:
    generate-ddl: true
    database: MYSQL
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        jdbc:
          lob:
            non_contextual_creation: true
        ddl-auto: update
        show_sql: true
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          # 구글 로그인 추가
          google:
            client-id: 563718306888-kbi0110t7l8qu2dcau8ohj5dp8vkn43l.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile
            redirect-uri: https://xn--o55b91v.xn--2i0b10rqve.xn--3e0b707e/login/oauth2/code/google
file-path:
  upload-path: '/storage/'

