services:
  certbot:
    image: certbot/certbot:latest
    container_name: cmd_certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email leehyeokju1@gmail.com --agree-tos --no-eff-email -d xn--bh3b89qjsa.xn--oi2b61z32a.xn--3e0b707e
    volumes:
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www:/var/www/certbot:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    depends_on:
      - web

  web:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      - TZ=Asia/Seoul
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt:rw
      - ./certbot/www:/var/www/certbot:rw
    depends_on:
      - was

  was:
    image: fada2020/wonjang-app-image
    container_name: was
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - TZ=Asia/Seoul
    entrypoint:
      - "java"
      - "-Xms256m"            # 초기 힙 메모리 설정
      - "-Xmx512m"            # 최대 힙 메모리 설정
      - "-jar"
      - "-Dspring.profiles.active=prod"
      - "/app.jar"
    volumes:
      - /home/wonjang/resume:/resume
      - /home/wonjang/storage:/storage
      - /home/wonjang/log:/var/log
      - /home/wonjang/logs/app-prod:/logs/app-prod
    depends_on:
      - db

  db:
    image: mariadb
    container_name: wonjang_db
    restart: always
    environment:
      - TZ=Asia/Seoul
      - MARIADB_DATABASE=wonjang_schema
      - MARIADB_USER=fada2020
      - MARIADB_PASSWORD=dnjswkd0731
      - MARIADB_ROOT_PASSWORD=dnjswkd0731
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  prometheus:
    image: prom/prometheus:v2.37.6
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data:/prometheus
    ports:
      - "9090:9090"
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    restart: always
    depends_on:
      - was

  grafana:
    image: grafana/grafana:9.4.7
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/volume:/var/lib/grafana
    restart: always
    depends_on:
      - was